server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.module
  mapper-locations:
    - mapper/*
